### ISSUE TITLE
At least one block type is required - when creating new payment form

### ISSUE THREAD

**Issue by shornuk** [enupal/stripe#121]
### Description
Fresh install, trying to create a payment form on local. Get error `At least one block type is required.` then when freshed it shows a payment form exists, but when trying to edit it, the same error comes up.

### Additional info

- Craft version: 3.4.30
- PHP version: 7.3.11
- Plugin version: 2.7.2

**Comment by andrelopez** [comment]
@shornuk Do you have project config enabled?

**Comment by shornuk** [comment]
I do, yes.

**Comment by andrelopez** [comment]
@shornuk Could you please try the next steps:

- remove the config/project.yaml (we'll rebuild it on next steps)
- Uninstall the plugin
- Install the plugin
- On your terminal run 
`php craft project-config/rebuild`

**Comment by shornuk** [comment]
I've tried that (saw it on another issue) but when I run the rebuild I get an `undefined index` error

**Comment by shornuk** [comment]
OK, managed to uninstall, reinstall, then ran the `project-config/rebuild` command and get the `Undefined index: ` error.

**Comment by shornuk** [comment]
Sorry to press on this but is there any update? I'm stuck with a site that I can't use or uninstall this plugin at the moment.

**Comment by shornuk** [comment]
So I've managed to make some progress. Went through and have manually cleaned up the database and project config. There's a lot of tables etc left in by the plugin. Cleared them all but would still get the `undefined index` error on rebuild. 

Decided to take the plunge and update to 3.5 RC. This went smoothly and the config now rebuilds. Bit of further cleaning and I think we're all good. 

Tried to install the plugin again and I'm getting errors on install. Would it be safe to assume it's not 3.5 ready?

**Comment by sunscreem** [comment]
@andrelopez Just ran into this myself (I'm on 3.5.1). Any suggestions? I can't create a form.

**Comment by shornuk** [comment]
@sunscreem - I'm not sure what the recommended way to fix this is, but for me it included a lot of uninstalling, manually cleaning up database tables, removing fields etc. It wasn't pretty. There's an issue with project config, hopefully a fix will come.

**Comment by andrelopez** [comment]
I'm looking deeply into this issue. @sunscreem did you get the error on a fresh install? Could you please tell me step by step how to recreate the issue?

**Comment by bymayo** [comment]
Also getting this issue with a fresh install on a site I recently updated to 3.5.5

When creating any new form, I get the error, then I go to Payment Forms and I can see the form is there, but when I try to edit it, the same error appears.

Project config is turned off.

**Comment by andrelopez** [comment]
@bymayo thanks for reporting. I'm still working on a solution to this issue.

**Comment by andrelopez** [comment]
Hi @shornuk @sunscreem  @bymayo I was finally able to recreate this issue and we just released Stripe Payments v3.0.2 with a fix to this bug related to project config. 

Please follow the next instructions:
- remove the next folders `storage/config/config-deltas` and `storage/config/runtime`
- Uninstall the plugin
- Update the plugin
- Install the plugin again

Please let me know how it goes.

**Comment by bymayo** [comment]
@andrelopez I've followed these steps but I'm still seeing the error running 3.0.2

**Comment by andrelopez** [comment]
@bymayo Thanks for the update! this usually comes up for new users. 

I'll leave this note here is you're a user with orders please contact us to support@enupal.com
